var jokes = [
  "What diet did the ghost developer go on? Booooooooooooolean!",
  "Why was the developer unhappy at their job? They wanted arrays. (A raise!)",
  "Why was the function sad after a successful first call? It didn’t get a callback.",
  "What's the object-oriented way to become wealthy? Inheritance.",
  "Why don't bachelors like Git? Because they are afraid to commit.",
  "A SQL query goes into a bar, walks up to two tables and asks: Can I JOIN you?",
  "What did JavaScript call his son? JSON!",
  "You know what the best thing about booleans is? Even if you are wrong, you are only off by a bit.",
  "What do you do when you can't understand your husband's behavior? man man. (Manual pages in Linux).",
  "How many developers does it take to change a light bulb? None. It's a hardware issue!",
  "A SQL developer walked into a NoSQL bar. They left because they couldn't find a table.",
  "How do you help JS errors? You <code>console</code> them!",
  "Why didn't the <code>div</code> get invited to the dinner party? Because it had no <code>class</code>!",
  "I've got a great UDP joke but I'm afraid you wouldn't get it...",
  "There are 10 types of people in this world, those who understand binary and those who don't.",
  "Why can't SQL and NoSQL Developers date one other? Because they don't agree on relationships.",
  "Where did the API go to eat? To the RESTaurant!",
  "**-** Knock Knock!**-** An async function**-** Who's there?",
  "What accommodations did the JavaScript developer request at the hotel? A room with a Vue!",
  "Why did the web developer always go to the wrong hotel room? They were in room 301!",
  "What did the command line die of? A Terminal illness.",
  "Why do developers use mechanical keyboards? To strongly type their code.",
  "Did you hear about the programmer that was scared of IDEs? They retreated back into their shell!",
  "What do you call optimistic front-end developers? Stack half-full developers.",
  "Hey officer! How did the hackers escape? No idea. They just ransomware.",
  "Why do Front-End Developers eat lunch alone? Because, they don't know how to join tables.",
  "What advice do you give to a JS developer who has never played baseball? Try catch.",
  "Why did the geek add <code>body { padding-top: 1000px; }</code> to his Facebook profile? He wanted to keep a low profile.",
  "Why was the developer unable to find his room? His room card said 404!",
  "How do you comfort a JS bug? You console it!",
  "Why do programmers prefer dark mode? Because light attracts bugs!",
  "Want to know the biggest lie in the universe? I have read and agreed to the terms and conditions.",
];

module.exports = jokes;
